name: subcellular
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
  - pyarrow
  - shapely
  - geopandas
  - networkx
  - statsmodels
  - pytest
  - anndata
  - astropy
  - pip
  - pip:
      - xgboost
      - joblib
      - kneed
      - minisom

